# Generated by Django 4.2.16 on 2024-10-01 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_clientes_providers_roles_remove_product_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Usuarios',
        ),
    ]
