# Generated by Django 4.2.16 on 2024-10-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_users_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_product',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
