# Generated by Django 4.2.16 on 2024-10-01 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_id_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('id_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sales')),
            ],
        ),
    ]
