# Generated by Django 4.2.16 on 2024-10-02 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_salescart_id_client_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='salesCart',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='id_product',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='id_provider',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='salescart',
            name='id_sale',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.sales'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
