# Generated by Django 4.2.16 on 2024-10-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_cartitem_salescart_remove_sales_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='providers', through='products.productsProviders', to='products.product'),
        ),
    ]
