# Generated by Django 4.2.16 on 2024-10-02 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_privider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='privider',
        ),
        migrations.AddField(
            model_name='product',
            name='privider',
            field=models.OneToOneField(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.providers'),
            preserve_default=False,
        ),
    ]
