# Generated by Django 4.2.16 on 2024-10-02 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_privider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='privider',
        ),
    ]
