# Generated by Django 4.2.16 on 2024-10-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_providers_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/'),
        ),
    ]
